version: "3.8"
services:
  db:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    networks:
      - url_shortener
networks:
  url_shortener:
